changelog:
  exclude:
    labels:
      - ignore-for-release
      - duplicate
      - invalid
      - question
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
        - semver-major
    - title: New Features
      labels:
        - enhancement
        - feature
        - semver-minor
    - title: Fixes
      labels:
        - bug
        - fix
        - regression
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Maintenance
      labels:
        - chore
        - dependencies
        - refactor
    - title: Other Changes
      labels:
        - '*'
